name: Build and upload binaries to release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Build and Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: rsuuid
            asset_name: rsuuid-linux-amd64
            rust: stable
          - os: macos-latest
            artifact_name: rsuuid
            asset_name: rsuuid-macos-amd64
            rust: stable
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rust
        run: rustup install ${{ matrix.rust }}

      - name: Build project
        run: cargo build --release --locked && strip target/release/rsuuid

      - name: Upload binaries to release
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.asset_name }}
          path: ${{ matrix.artifact_name }}
