name: Build

on: pull_request_target
permissions:
  pull-requests: write
  contents: write

jobs:
  release:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: rsuuid
            asset_name: rsuuid-linux-amd64
            rust: stable
          - os: macos-latest
            artifact_name: rsuuid
            asset_name: rsuuid-macos-amd64
            rust: stable
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rust
        run: rustup install ${{ matrix.rust }}

      - name: Build project
        run: cargo build --release --locked && strip target/release/rsuuid
