name: Build and upload binaries to release

on:
  push:
    tags:
      - '*'
permissions:
  contents: write

jobs:
  release:
    name: Build and Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: rsuuid
            asset_name: rsuuid-linux-amd64
            rust: stable
          - os: macos-latest
            artifact_name: rsuuid
            asset_name: rsuuid-macos-amd64
            rust: stable
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rust
        run: rustup install ${{ matrix.rust }}

      - name: Build project
        run: cargo build --release --locked && strip target/release/rsuuid

      - name: Upload binaries to release
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.asset_name }}
          path: target/release/${{ matrix.artifact_name }}

      - run: cp -v target/release/${{ matrix.artifact_name }} target/release/${{ matrix.asset_name }}

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/release/${{ matrix.asset_name }}

      - name: Bump homebrew-core formula
        uses: mislav/bump-homebrew-formula-action@v1
        if: "matrix.os == 'macos-latest' && !contains(github.ref, '-')" # skip prereleases
        env:
          COMMITTER_TOKEN: ${{ secrets.HOMEBREW_GITHUB_TOKEN }}
        with:
          homebrew-tap: dgorohov/homebrew-home
          formula-name: rsuuid
